sc

diff --git a/.github/workflows/30-shorebird-ios-release_prod.yml b/.github/workflows/30-shorebird-ios-release_prod.yml
--- a/.github/workflows/30-shorebird-ios-release_prod.yml
+++ b/.github/workflows/30-shorebird-ios-release_prod.yml
@@ -14,6 +14,22 @@ jobs:
       SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
     steps:
       - uses: actions/checkout@v6
+      - uses: apple-actions/import-codesign-certs@v3
+        with:
+          p12-filepath: ios/certificate.p12  
+          p12-password: ${{ secrets.P12_PASSWORD }}
+          keychain: signing_temp
+          create-keychain: true  
+      - run: |
+          PP_PATH="$HOME/Library/MobileDevice/Provisioning Profiles"
+          mkdir -p "$PP_PATH"
+          if [ -f "ios/muein_prod.mobileprovision" ]; then
+            cp ios/muein_prod.mobileprovision "$PP_PATH/"
+            echo "Provisioning profile copied successfully."
+          else
+            echo "Error: Provisioning profile not found in ios/"
+            exit 1
+          fi      
       - uses: actions/cache@v4
         with:
           path: ios/Pods
@@ -42,12 +58,6 @@ jobs:
           flutter-version-file: pubspec.yaml
           channel: "stable"
           cache: true
-      - uses: apple-actions/import-codesign-certs@v3
-        with:
-          p12-filepath: ios/certificate.p12  
-          p12-password: ${{ secrets.P12_PASSWORD }}
-          keychain: signing_temp
-          create-keychain: true    
       - env:
           PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
         run: |
@@ -57,25 +67,6 @@ jobs:
       - uses: shorebirdtech/setup-shorebird@v1
         with:
           cache: true
-      - shell: bash 
-        run: |
-           KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
-           security create-keychain -p "temporary_password" $KEYCHAIN_PATH
-           security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
-           security unlock-keychain -p "temporary_password" $KEYCHAIN_PATH
-           P12_FILE="ios/certificate.p12"
-           if [ -f "$P12_FILE" ]; then
-             security import $P12_FILE -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
-           else
-             echo "Error: Certificate file not found at $P12_FILE"
-             exit 1
-           fi
-           security list-keychain -d user -s $KEYCHAIN_PATH
-           PP_PATH="$HOME/Library/MobileDevice/Provisioning Profiles"
-           mkdir -p "$PP_PATH"
-           if [ -f "ios/muein_prod.mobileprovision" ]; then
-             cp ios/muein_prod.mobileprovision "$PP_PATH/"
-           fi
       - uses: actions/cache@v4
         with:
           path: ~/.pub-cache
