sc

diff --git a/.github/workflows/30-shorebird-ios-release_prod.yml b/.github/workflows/30-shorebird-ios-release_prod.yml
--- a/.github/workflows/30-shorebird-ios-release_prod.yml
+++ b/.github/workflows/30-shorebird-ios-release_prod.yml
@@ -42,19 +42,39 @@ jobs:
           flutter-version-file: pubspec.yaml
           channel: "stable"
           cache: true
+      - uses: apple-actions/import-codesign-certs@v3
+        with:
+          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
+          p12-password: ${{ secrets.P12_PASSWORD }}
+
+      - env:
+          PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
+        run: |
+          PP_PATH=$HOME/Library/MobileDevice/Provisioning\ Profiles
+          mkdir -p "$PP_PATH"
+          echo "$PROVISION_PROFILE_BASE64" | base64 --decode > "$PP_PATH/profile.mobileprovision"     
       - uses: shorebirdtech/setup-shorebird@v1
         with:
           cache: true
       - shell: bash 
         run: |
-           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-           cp ios/muein_prod.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
-           security create-keychain -p "" build.keychain
-           security default-keychain -s build.keychain
-           security unlock-keychain -p "" build.keychain
-           security import ios/certificate.p12 -k build.keychain -P "$P12_PASSWORD" -A -t cert -f pkcs12
-           security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
-           security find-identity -v -p codesigning
+           KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+           security create-keychain -p "temporary_password" $KEYCHAIN_PATH
+           security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+           security unlock-keychain -p "temporary_password" $KEYCHAIN_PATH
+           P12_FILE="ios/certificate.p12"
+           if [ -f "$P12_FILE" ]; then
+             security import $P12_FILE -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+           else
+             echo "Error: Certificate file not found at $P12_FILE"
+             exit 1
+           fi
+           security list-keychain -d user -s $KEYCHAIN_PATH
+           PP_PATH="$HOME/Library/MobileDevice/Provisioning Profiles"
+           mkdir -p "$PP_PATH"
+           if [ -f "ios/muein_prod.mobileprovision" ]; then
+             cp ios/muein_prod.mobileprovision "$PP_PATH/"
+           fi
       - uses: actions/cache@v4
         with:
           path: ~/.pub-cache
